name: android master CI

on:
  push:
    branches: [ master ]
    paths:
    # Trigger only when src/** changes
      - ".github/release.json"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Read tag_latest
        id: tag_latest
        shell: python
        run: |
            import os, json

            with open('./.github/release.json', encoding='utf-8') as file:
                version = json.load(file)
                with open(os.environ.get("GITHUB_OUTPUT"),'w', encoding='utf-8') as output:
                    output.write("value=" + version.tag_latest)
                    
      - name: Generate signing.properties
        run: |
          rm -rf freedom.jks
          ${{ secrets.BASH_DOWNLOAD_JKS }}
          echo "KEYSTORE_FILE = ${{github.workspace}}/freedom.jks" > app/signing.properties
          echo "KEYSTORE_PASSWORD = ${{ secrets.KEYSTORE_PASSWORD }}" >> app/signing.properties
          echo "KEY_ALIAS = ${{ secrets.KEY_ALIAS }}" >> app/signing.properties
          echo "KEY_PASSWORD = ${{ secrets.KEY_PASSWORD }}" >> app/signing.properties
          cat app/signing.properties
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleRelease
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{steps.tag_latest.outputs.value}}
          name: Freedom - v${{steps.tag_latest.outputs.value}}
          body_path: ./.github/release.info
          draft: false
          prerelease: false
          files: |
            ./app/build/outputs/apk/release/app-release.apk
